### ISSUE TITLE
Pkg.generate creates appveyor configuration for Julia 0.3

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13884]
Pkg.generate with Julia 0.4 still creates an `appveyor.yml` file for Julia 0.3:
```yaml
environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x86/0.3/julia-0.3-latest-win32.exe"
  - JULIAVERSION: "julialang/bin/winnt/x64/0.3/julia-0.3-latest-win64.exe"
  - JULIAVERSION: "julianightlies/bin/winnt/x86/julia-latest-win32.exe"
  - JULIAVERSION: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"
```
