### ISSUE TITLE
Pkg3 -- resolve fails with unsatisfiable restricted versions on `dev`

### ISSUE THREAD

**Issue by chriselrod** [JuliaLang/julia#28639]
I commented here:
https://discourse.julialang.org/t/where-does-pkg-3-find-version-numbers/12330/15

Incorrectly, I thought deleting everything would help.
I deleted the packages, registries, and environments/v1.0 directories.
Now:
```julia
(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`

(v1.0) pkg> dev https://github.com/chriselrod/TriangularMatrices.jl
  Updating git-repo `https://github.com/chriselrod/TriangularMatrices.jl`
   Cloning default registries into /home/chris/.julia/registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
[ Info: Assigning UUID 0738bffa-c6bd-5282-9c9b-a1d83e73ef17 to TriangularMatrices
[ Info: Path `/home/chris/.julia/dev/TriangularMatrices` exists and looks like the correct package, using existing path instead of cloning
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package TriangularMatrices [0738bffa]:
 TriangularMatrices [0738bffa] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─TriangularMatrices [0738bffa] is fixed to version 0.1.0
 └─restricted to versions 0.0.0 by an explicit requirement — no versions left
```

The Project.toml file looks like this:
```toml
name = "TriangularMatrices"
uuid = "5ebe76dc-7dd7-11e8-2992-2706ab89a682"
authors = ["chriselrod <elrodc@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
```

I'm switching my projects that currently depend on it to use something else, meaning this itself isn't very urgent. But I wanted to run a couple benchmarks, and this itself is something I really don't understand -- so I'd like to be pointed in the right direction, figure out how I can actually solve problems like this reasonably quickly in the future. I don't want to feel like I'm fighting the package manager!

As a feature request -- when resolution fails, can it print out the sources of the conflicting requirements? This would make debugging issues much easier.
