### ISSUE TITLE
Program variable gets silently changed (memory corruption)

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#32215]
An Int variable in my program is getting silently corrupted.  This is for Windows 10, 64-bit, Julia 1.1.0.  Unfortunately, despite my efforts to trim it, my minimal code example is long, and there is a big data file needed to expose the error.  Furthermore, the code needs to run multiple times before the corruption occurs. The code is here: https://gist.github.com/StephenVavasis/7021abd7bb76244f91bb254a83d712c0
and the data file is here:
https://gist.github.com/StephenVavasis/9ba73439df50389a5c88ece4aaf397ca

To run this example, save the code as thrbs1.jl and the data file as testmesh.dat, and then use `include("thrbs1.jl")` which loads and executes the code 500 times.  The error occurs usually before the 100th time.

Here is the output I get.  The bottom part indicates that the variable `nnode0_sample` has been silently corrupted.
```
julia> include("thrbs1.jl")
WARNING: replacing module test1.
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
nnode0_sample has changed
ERROR: LoadError: W
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] problemsetup0(::Float64) at C:\Users\vavasis\ownCloud\Documents\Katerina\cohesive\conic_jl\thrbs1.jl:65
 [3] top-level scope at C:\Users\vavasis\ownCloud\Documents\Katerina\cohesive\conic_jl\thrbs1.jl:192 [inlined]
 [4] top-level scope at .\none:0
 [5] include at .\boot.jl:326 [inlined]
 [6] include_relative(::Module, ::String) at .\loading.jl:1038
 [7] include(::Module, ::String) at .\sysimg.jl:29
 [8] include(::String) at .\client.jl:403
 [9] top-level scope at none:0
in expression starting at C:\Users\vavasis\ownCloud\Documents\Katerina\cohesive\conic_jl\thrbs1.jl:191

julia>
```

**Comment by StephenVavasis** [comment]
The same issue remains in 1.1.1 and 1.2.0-rc1; earlier I tried this code in a fresh install of each and observed the same error.

**Comment by vtjnash** [comment]
I can confirm the bug. It has forgotten to hold onto a gc root for the load, with either of tbaa_const or invariant.load independently sufficient to permit it to reorder the instruction stream and trigger the failure result.

**Comment by vtjnash** [comment]
The liveness analysis looks correct for the load (the value we care about is %92), but it seems like %pass9 may be clobbering the gc slot (%gcframe+3 for %88) early: https://gist.github.com/vtjnash/326296187837f44fc235f65e498f9ac6

```
Liveness analysis for BB L156
        Defs: 
        PhiOuts: %jl_value_t addrspace(10)* %429
        UpExposedUsesUnrooted: %jl_value_t addrspace(10)* %96, %jl_value_t addrspace(10)* %92, %jl_value_t addrspace(10)* %408
        UpExposedUses: 
        LiveIn: %jl_value_t addrspace(10)* %97, %jl_value_t addrspace(10)* %96, %jl_value_t addrspace(10)* %92, %jl_value_t addrspace(10)* %408, %jl_value_t addrspace(10)* %429, %jl_value_t addrspace(10)* %442, %jl_value_t addrspace(10)* %421, %jl_value_t addrspace(10)* %425
        LiveOut: %jl_value_t addrspace(10)* %97, %jl_value_t addrspace(10)* %429, %jl_value_t addrspace(10)* %442, %jl_value_t addrspace(10)* %421, %jl_value_t addrspace(10)* %425
```

```diff
@@ -1998,6 +2000,8 @@ bool LateLowerGCFrame::runOnFunction(Function &F) {
     ComputeLiveness(S);
     std::vector<int> Colors = ColorRoots(S);
     std::map<Value *, std::pair<int, int>> CallFrames; // = OptimizeCallFrames(S, Ordering);
+    _jl_dump_function(&F);
+    dumpLivenessState(F, S);
     PlaceRootsAndUpdateCalls(Colors, S, CallFrames);
     CleanupIR(F, &S);
     return true;
```
