### ISSUE TITLE
Сompat does not include DEV version

### ISSUE THREAD

**Issue by gryumov** [JuliaLang/julia#49944]
Сompat does not include DEV version

```toml
name = "Coconut"
uuid = "26c37dcc-07de-4b08-afb5-6df828475b25"
authors = ["foo <foo@foo.com>"]
version = "0.1.0-dev"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Foo = "01ba1978-7efe-11ed-2893-03bfe3abf75a"

[compat]
Foo = "0.5.0-dev"
julia = "1.8"
```

```julia
caused by: invalid version specifier: "0.5.0-dev"
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
```
