### ISSUE TITLE
Extension not loaded if trigger is a strong dependency

### ISSUE THREAD

**Issue by topolarity** [JuliaLang/julia#55723]
```toml
# Project.toml
name = "Foo"
uuid = "0a21ebe4-285f-4d3c-b082-40545a858146"
authors = ["Cody Tapscott <topolarity@tapscott.me>"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[extensions]
ModelingToolkitFooExt = ["ModelingToolkit"]
```
```julia
# ext/ModelingToolkitFooExt/ModelingToolkitFooExt.jl
module ModelingToolkitFooExt

using ModelingToolkit
using Foo

println("loaded ext")

end # ModelingToolkitFooExt
```

The extension does not load when doing `using Foo, ModelingToolkit`:
```julia
julia> using Foo, ModelingToolkit

julia> Base.get_extension(Foo, :ModelingToolkitFooExt) === nothing
true
```

```julia
julia> versioninfo()
Julia Version 1.10.5
Commit 6f3fdf7b362 (2024-08-27 14:19 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i7-1255U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
```

Related: https://github.com/JuliaLang/Pkg.jl/issues/3797
