### ISSUE TITLE
`require`ing PkgId that is getting precompiled now triggers loading deadlock detector

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#57866]
```toml
# Project.toml
name = "RecursiveLoad"
uuid = "efbca400-5100-403c-819d-b99f42c4d285"
version = "0.1.0"
```

```julia
module RecursiveLoad

id = Base.PkgId(Base.UUID("efbca400-5100-403c-819d-b99f42c4d285"), "RecursiveLoad")
Base.require(id)
# Base.require(@__MODULE__, :RecursiveLoad) # this is ok

end # module RecursiveLoad
```

```julia
ERROR: LoadError: ConcurrencyViolationError("deadlock detected in loading RecursiveLoad using RecursiveLoad")
Stacktrace:
  [1] canstart_loading(modkey::Base.PkgId, build_id::UInt128, stalecheck::Bool)
    @ Base ./loading.jl:2219
  [2] start_loading(modkey::Base.PkgId, build_id::UInt128, stalecheck::Bool)
    @ Base ./loading.jl:2227
  [3] _require_prelocked(uuidkey::Base.PkgId, env::Nothing)
```

Causes e.g. https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ed23a99_vs_8561cc3/Images.primary.log.
